🏠 take owned labels for deferred inc
 ### Overview

    This is a small but important breaking change to the
    `IntCounterWithLabels` API, surrounding the lifetimes of labels.

 ### Motivation

    When integrating these labeled counters in asynchronous code,
    difficulties surrounding lifetimes and ownership arise. An example
    error is shown below:

```
error[E0505]: cannot move out of `example_labels` because it is borrowed
   --> src/program.rs:123:456
    |
123 |           COUNTER.deferred_inc(&example_labels);
    |                                    ---------------------- borrow of `example_labels` occurs here
...
200 | /         object
201 | |             .async_fn()
202 | |             // Then, add the following instrumentation to the future...
203 | |             .into_instrumented_future()
...   |
300 | |             .map(move |res| {
    | |                  ^^^^^^^^^^^ move out of `example_labels` occurs here
...   |
XXX | |                         example_labels,
    | |                         ------------- move occurs due to use in closure
...   |
XXX | |                 res
XXX | |             })
    | |______________- returning this value requires that `example_labels` is borrowed for `'static`
```

    When working with counters that are `'static`, it turned out that
    incrementing them would similarly require a static set of labels.

    Because label enums are in practice, simple enums without payloads,
    which can be made to derive `Clone` and `Copy`, this API should be
    more ergonomic in practice, and removes the need to preface literals
    with `&`s.